user root;
worker_processes 1;

events {

}

http {
    server {
        listen      80;
        server_name 5.101.7.211;
        
        location / {
            proxy_pass http://backend:3000/;
        }
    }

}